/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LiquidityManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEAD_ADDRESS"
      | "LOCK_1_MIN"
      | "LOCK_1_MONTH"
      | "LOCK_5_MINS"
      | "LOCK_6_MONTHS"
      | "addLiquidity"
      | "admin"
      | "getLPLockInfoByPair"
      | "handleLPManagement"
      | "lpLockInfoByPair"
      | "owner"
      | "removeLiquidity"
      | "renounceOwnership"
      | "router"
      | "setAdmin"
      | "setUnicryptLocker"
      | "transferOwnership"
      | "unicryptLocker"
      | "unicryptLockerAddress"
      | "unlockLP"
      | "withdrawETH"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "LPLockedWithUnicrypt"
      | "LPTokensBurned"
      | "LPTokensLocked"
      | "LPTokensUnlocked"
      | "LPUnlockedFromUnicrypt"
      | "LiquidityRemoved"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEAD_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_1_MIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_1_MONTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_5_MINS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_6_MONTHS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getLPLockInfoByPair",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleLPManagement",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lpLockInfoByPair",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUnicryptLocker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unicryptLocker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unicryptLockerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unlockLP",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEAD_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "LOCK_1_MIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_1_MONTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_5_MINS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_6_MONTHS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLPLockInfoByPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleLPManagement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lpLockInfoByPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUnicryptLocker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unicryptLocker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unicryptLockerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlockLP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LPLockedWithUnicryptEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    lpPair: AddressLike,
    amount: BigNumberish,
    unlockDate: BigNumberish,
    lockId: BigNumberish,
    lockIndex: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    lpPair: string,
    amount: bigint,
    unlockDate: bigint,
    lockId: bigint,
    lockIndex: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    lpPair: string;
    amount: bigint;
    unlockDate: bigint;
    lockId: bigint;
    lockIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LPTokensBurnedEvent {
  export type InputTuple = [tokenAddress: AddressLike, lpAmount: BigNumberish];
  export type OutputTuple = [tokenAddress: string, lpAmount: bigint];
  export interface OutputObject {
    tokenAddress: string;
    lpAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LPTokensLockedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    lpAmount: BigNumberish,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    lpAmount: bigint,
    unlockTime: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    lpAmount: bigint;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LPTokensUnlockedEvent {
  export type InputTuple = [tokenAddress: AddressLike, lpAmount: BigNumberish];
  export type OutputTuple = [tokenAddress: string, lpAmount: bigint];
  export interface OutputObject {
    tokenAddress: string;
    lpAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LPUnlockedFromUnicryptEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    lpPair: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    lpPair: string,
    amount: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    lpPair: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [amountA: BigNumberish, amountB: BigNumberish];
  export type OutputTuple = [amountA: bigint, amountB: bigint];
  export interface OutputObject {
    amountA: bigint;
    amountB: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LiquidityManager extends BaseContract {
  connect(runner?: ContractRunner | null): LiquidityManager;
  waitForDeployment(): Promise<this>;

  interface: LiquidityManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEAD_ADDRESS: TypedContractMethod<[], [string], "view">;

  LOCK_1_MIN: TypedContractMethod<[], [bigint], "view">;

  LOCK_1_MONTH: TypedContractMethod<[], [bigint], "view">;

  LOCK_5_MINS: TypedContractMethod<[], [bigint], "view">;

  LOCK_6_MONTHS: TypedContractMethod<[], [bigint], "view">;

  addLiquidity: TypedContractMethod<
    [
      token: AddressLike,
      lpOwner: AddressLike,
      tokenAmount: BigNumberish,
      ethAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  getLPLockInfoByPair: TypedContractMethod<
    [lpPair: AddressLike],
    [
      [boolean, bigint, bigint, string, bigint] & {
        isUnicryptLocked: boolean;
        unicryptUnlockDate: bigint;
        unicryptLockAmount: bigint;
        lockOwner: string;
        lockIndex: bigint;
      }
    ],
    "view"
  >;

  handleLPManagement: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      lpPair: AddressLike,
      dev: AddressLike,
      lpManagementOption: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  lpLockInfoByPair: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, string] & {
        isLocked: boolean;
        lockId: bigint;
        lockIndex: bigint;
        lockAmount: bigint;
        lockDate: bigint;
        unlockDate: bigint;
        lockOwner: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeLiquidity: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [[bigint, bigint]],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  router: TypedContractMethod<[], [string], "view">;

  setAdmin: TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;

  setUnicryptLocker: TypedContractMethod<
    [_unicryptLocker: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unicryptLocker: TypedContractMethod<[], [string], "view">;

  unicryptLockerAddress: TypedContractMethod<[], [string], "view">;

  unlockLP: TypedContractMethod<
    [tokenAddress: AddressLike, lpPair: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawETH: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawToken: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEAD_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LOCK_1_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_1_MONTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_5_MINS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_6_MONTHS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [
      token: AddressLike,
      lpOwner: AddressLike,
      tokenAmount: BigNumberish,
      ethAmount: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLPLockInfoByPair"
  ): TypedContractMethod<
    [lpPair: AddressLike],
    [
      [boolean, bigint, bigint, string, bigint] & {
        isUnicryptLocked: boolean;
        unicryptUnlockDate: bigint;
        unicryptLockAmount: bigint;
        lockOwner: string;
        lockIndex: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "handleLPManagement"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      lpPair: AddressLike,
      dev: AddressLike,
      lpManagementOption: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lpLockInfoByPair"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, string] & {
        isLocked: boolean;
        lockId: bigint;
        lockIndex: bigint;
        lockAmount: bigint;
        lockDate: bigint;
        unlockDate: bigint;
        lockOwner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike],
    [[bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "router"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAdmin"
  ): TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUnicryptLocker"
  ): TypedContractMethod<[_unicryptLocker: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unicryptLocker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unicryptLockerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unlockLP"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, lpPair: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawETH"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "LPLockedWithUnicrypt"
  ): TypedContractEvent<
    LPLockedWithUnicryptEvent.InputTuple,
    LPLockedWithUnicryptEvent.OutputTuple,
    LPLockedWithUnicryptEvent.OutputObject
  >;
  getEvent(
    key: "LPTokensBurned"
  ): TypedContractEvent<
    LPTokensBurnedEvent.InputTuple,
    LPTokensBurnedEvent.OutputTuple,
    LPTokensBurnedEvent.OutputObject
  >;
  getEvent(
    key: "LPTokensLocked"
  ): TypedContractEvent<
    LPTokensLockedEvent.InputTuple,
    LPTokensLockedEvent.OutputTuple,
    LPTokensLockedEvent.OutputObject
  >;
  getEvent(
    key: "LPTokensUnlocked"
  ): TypedContractEvent<
    LPTokensUnlockedEvent.InputTuple,
    LPTokensUnlockedEvent.OutputTuple,
    LPTokensUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "LPUnlockedFromUnicrypt"
  ): TypedContractEvent<
    LPUnlockedFromUnicryptEvent.InputTuple,
    LPUnlockedFromUnicryptEvent.OutputTuple,
    LPUnlockedFromUnicryptEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "LPLockedWithUnicrypt(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      LPLockedWithUnicryptEvent.InputTuple,
      LPLockedWithUnicryptEvent.OutputTuple,
      LPLockedWithUnicryptEvent.OutputObject
    >;
    LPLockedWithUnicrypt: TypedContractEvent<
      LPLockedWithUnicryptEvent.InputTuple,
      LPLockedWithUnicryptEvent.OutputTuple,
      LPLockedWithUnicryptEvent.OutputObject
    >;

    "LPTokensBurned(address,uint256)": TypedContractEvent<
      LPTokensBurnedEvent.InputTuple,
      LPTokensBurnedEvent.OutputTuple,
      LPTokensBurnedEvent.OutputObject
    >;
    LPTokensBurned: TypedContractEvent<
      LPTokensBurnedEvent.InputTuple,
      LPTokensBurnedEvent.OutputTuple,
      LPTokensBurnedEvent.OutputObject
    >;

    "LPTokensLocked(address,uint256,uint256)": TypedContractEvent<
      LPTokensLockedEvent.InputTuple,
      LPTokensLockedEvent.OutputTuple,
      LPTokensLockedEvent.OutputObject
    >;
    LPTokensLocked: TypedContractEvent<
      LPTokensLockedEvent.InputTuple,
      LPTokensLockedEvent.OutputTuple,
      LPTokensLockedEvent.OutputObject
    >;

    "LPTokensUnlocked(address,uint256)": TypedContractEvent<
      LPTokensUnlockedEvent.InputTuple,
      LPTokensUnlockedEvent.OutputTuple,
      LPTokensUnlockedEvent.OutputObject
    >;
    LPTokensUnlocked: TypedContractEvent<
      LPTokensUnlockedEvent.InputTuple,
      LPTokensUnlockedEvent.OutputTuple,
      LPTokensUnlockedEvent.OutputObject
    >;

    "LPUnlockedFromUnicrypt(address,address,uint256)": TypedContractEvent<
      LPUnlockedFromUnicryptEvent.InputTuple,
      LPUnlockedFromUnicryptEvent.OutputTuple,
      LPUnlockedFromUnicryptEvent.OutputObject
    >;
    LPUnlockedFromUnicrypt: TypedContractEvent<
      LPUnlockedFromUnicryptEvent.InputTuple,
      LPUnlockedFromUnicryptEvent.OutputTuple,
      LPUnlockedFromUnicryptEvent.OutputObject
    >;

    "LiquidityRemoved(uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
