/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  DividendPayingTokenOptionalInterface,
  DividendPayingTokenOptionalInterfaceInterface,
} from "../../../contracts/DividendTracker.sol/DividendPayingTokenOptionalInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "accumulativeDividendOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "withdrawableDividendOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "withdrawnDividendOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class DividendPayingTokenOptionalInterface__factory {
  static readonly abi = _abi;
  static createInterface(): DividendPayingTokenOptionalInterfaceInterface {
    return new Interface(_abi) as DividendPayingTokenOptionalInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DividendPayingTokenOptionalInterface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as DividendPayingTokenOptionalInterface;
  }
}
