/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IUnicryptV2LockerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "gFees"
      | "getNumLocksForToken"
      | "getUserLockForTokenAtIndex"
      | "getUserNumLocksForToken"
      | "lockLPToken"
      | "relock"
      | "transferLockOwnership"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "gFees", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getNumLocksForToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserLockForTokenAtIndex",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserNumLocksForToken",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockLPToken",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      boolean,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "relock",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferLockOwnership",
    values: [AddressLike, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "gFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNumLocksForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserLockForTokenAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserNumLocksForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockLPToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferLockOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export interface IUnicryptV2Locker extends BaseContract {
  connect(runner?: ContractRunner | null): IUnicryptV2Locker;
  waitForDeployment(): Promise<this>;

  interface: IUnicryptV2LockerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  gFees: TypedContractMethod<
    [],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        ethFee: bigint;
        secondaryFeeToken: string;
        secondaryTokenFee: bigint;
        secondaryTokenDiscount: bigint;
        liquidityFee: bigint;
        referralPercent: bigint;
        referralToken: string;
        referralHold: bigint;
        referralDiscount: bigint;
      }
    ],
    "view"
  >;

  getNumLocksForToken: TypedContractMethod<
    [_lpToken: AddressLike],
    [bigint],
    "view"
  >;

  getUserLockForTokenAtIndex: TypedContractMethod<
    [_user: AddressLike, _lpToken: AddressLike, _index: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        lockDate: bigint;
        amount: bigint;
        initialAmount: bigint;
        unlockDate: bigint;
        lockID: bigint;
        owner: string;
      }
    ],
    "view"
  >;

  getUserNumLocksForToken: TypedContractMethod<
    [_user: AddressLike, _lpToken: AddressLike],
    [bigint],
    "view"
  >;

  lockLPToken: TypedContractMethod<
    [
      _lpToken: AddressLike,
      _amount: BigNumberish,
      _unlock_date: BigNumberish,
      _referral: AddressLike,
      _fee_in_eth: boolean,
      _withdrawer: AddressLike
    ],
    [void],
    "payable"
  >;

  relock: TypedContractMethod<
    [
      _lpToken: AddressLike,
      _index: BigNumberish,
      _lockID: BigNumberish,
      _unlock_date: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferLockOwnership: TypedContractMethod<
    [
      _lpToken: AddressLike,
      _index: BigNumberish,
      _lockID: BigNumberish,
      _newOwner: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [
      _lpToken: AddressLike,
      _index: BigNumberish,
      _lockID: BigNumberish,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "gFees"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        ethFee: bigint;
        secondaryFeeToken: string;
        secondaryTokenFee: bigint;
        secondaryTokenDiscount: bigint;
        liquidityFee: bigint;
        referralPercent: bigint;
        referralToken: string;
        referralHold: bigint;
        referralDiscount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNumLocksForToken"
  ): TypedContractMethod<[_lpToken: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserLockForTokenAtIndex"
  ): TypedContractMethod<
    [_user: AddressLike, _lpToken: AddressLike, _index: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        lockDate: bigint;
        amount: bigint;
        initialAmount: bigint;
        unlockDate: bigint;
        lockID: bigint;
        owner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserNumLocksForToken"
  ): TypedContractMethod<
    [_user: AddressLike, _lpToken: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockLPToken"
  ): TypedContractMethod<
    [
      _lpToken: AddressLike,
      _amount: BigNumberish,
      _unlock_date: BigNumberish,
      _referral: AddressLike,
      _fee_in_eth: boolean,
      _withdrawer: AddressLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "relock"
  ): TypedContractMethod<
    [
      _lpToken: AddressLike,
      _index: BigNumberish,
      _lockID: BigNumberish,
      _unlock_date: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferLockOwnership"
  ): TypedContractMethod<
    [
      _lpToken: AddressLike,
      _index: BigNumberish,
      _lockID: BigNumberish,
      _newOwner: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [
      _lpToken: AddressLike,
      _index: BigNumberish,
      _lockID: BigNumberish,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
